import { TIP_COLOR_PRESETS } from './config'

export const GRASS_CONTROL_DEFAULTS = {
  bladeHeightMin: 0.4,
  bladeHeightMax: 0.8,
  bladeWidthMin: 0.01,
  bladeWidthMax: 0.05,
  bendAmountMin: 0.2,
  bendAmountMax: 0.6,
  bladeRandomness: { x: 0.3, y: 0.3, z: 0.2 },
  baseWidth: 0.35,
  tipThin: 0.9,
  thicknessStrength: 0.10,
  clumpSize: 1.5,
  clumpBlendSmoothness: 1,
  centerYaw: 0.1,
  bladeYaw: 1.2,
  clumpYaw: 2.7,
  tipColor: TIP_COLOR_PRESETS[0],
  baseColor: '#000000',
  bladeSeedRange: { x: 0.95, y: 1.03 },
  clumpSeedRange: { x: 0.9, y: 1.1 },
  aoPower: 5,
  midSoft: 0.25,
  rimPos: 0.42,
  rimSoft: 0.03,
  windDirX: 1,
  windDirZ: 0,
  windSpeed: 0.35,
  windStrength: 4.5,
  windScale: 0.1,
  windFacing: 1,
  swayFreqMin: 0.4,
  swayFreqMax: 1.5,
  swayStrength: 0.01,
  windDistanceStart: 50,
  windDistanceEnd: 100,
  pushRadius: 0.7,
  pushAmount: 0.4,
  flattenAmount: 0.05,
  lodNoiseScale: 0.1,
  cullOffset: 2,
  roughness: 0.35,
  metalness: 0.5,
  emissive: '#61ffef',
  envMapIntensity: 0.5,
}

export function createGrassControls() {
  return GRASS_CONTROL_DEFAULTS
}
